export interface QuickAction {
    title: string;
    description: string;
    gradient: string;
    href: string;
};

export const QuickActions: QuickAction[] = [
    {
        title: "Narrate a story",
        description: "Bring your stories to life with expressive AI narration.",
        gradient: "from-[#ff8ee3] to-[#57d7e0]",
        href: "/text-to-speech?=In a village nestled between rolling hills, there lived a young girl named Lily. She had a vivid imagination and loved to create stories about magical creatures and faraway lands. One day, she discovered an old book in her attic that contained a spell to bring stories to life. With a wave of her hand, she could narrate her tales and watch as they unfolded before her eyes. Her stories became so popular that people from all over the world would gather to listen to her enchanting voice and the adventures she created."
    },
    {
        title: "Create a podcast",
        description: "Easily produce engaging podcasts with AI-generated voices.",
        gradient: "from-[#fbbf24] to-[#f87171]",
        href: "/text-to-speech?=You are listening to a podcast generated by AI. This is a demo of the text-to-speech feature."
    },
    {
        title: "Generate voiceovers",
        description: "Produce professional voiceovers for videos and presentations.",
        gradient: "from-[#a78bfa] to-[#f472b6]",
        href: "/text-to-speech?=Welcome to our product demo. In this video, we will show you how to use our text-to-speech feature to create realistic voiceovers for your projects."
    },
    {
        title: "Translate text",
        description: "Convert your text into multiple languages with natural-sounding voices.",
        gradient: "from-[#34d399] to-[#3b82f6]",
        href: "/text-to-speech?=Hello, welcome to our translation demo. This is a simple example of how our text-to-speech feature can be used to translate text into different languages."
    },
    {
        title: "Create a blog post",
        description: "Generate engaging blog content with AI-powered writing assistance.",
        gradient: "from-[#ec4899] to-[#8b5cf6]",
        href: "/text-to-speech?=Welcome to our blog post generator. This is a simple example of how our text-to-speech feature can be used to create engaging blog content."
    },
    {
        title: "Generate a script",
        description: "Create professional scripts for videos, presentations, and more.",
        gradient: "from-[#06b6d4] to-[#6366f1]",
        href: "/text-to-speech?=This is a simple example of how our text-to-speech feature can be used to generate scripts for various media."
    },
];